### PR TITLE
Release/10.xx

### PR DESCRIPTION
**Pull request by serge-sans-paille**

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
Basically these commits pull in the getXXXPluginInfo from the compiler extension, which prevents some linking issues under some cmake configuration (namely when using libLLVM-10.so)

cc @sylvestre

**Comment by sylvestre** [comment]
Merci :)

**Comment by serge-sans-paille** [comment]
@tstellar / @sylvestre : patch updated in a less intrusive way

**Comment by sylvestre** [comment]
Seems to work, many thanks!

**Pull request merged**
